config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :travel_details do
    get :my_travel_details, on: :collection
    resources :orders
  end

  root to: 'home#homepage'
  get 'homepage', to: 'home#homepage'
  # custom route for get current user orders
  # from home controller
  get :current_user_orders, to: 'home#current_user_orders'

  get :api_key, to: 'home#api_key'

  # Routes For API Calls
  namespace :api do
    namespace :v1 do
      resources :travel_details do
        resources :orders
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/travel_detail.rb
class TravelDetail < ApplicationRecord

  # associations
  belongs_to :user
  has_many :orders, dependent: :destroy

  # Scopes
  scope :get_current_user_travel_details, -> (current_user_id) { where(:user_id => current_user_id) }

  #Method to Search a Specific Record
  def self.search(from_search, to_search)

    if from_search.present? && to_search.present?
      return TravelDetail.where("\"from\" like ?", "%#{from_search}%").where("\"to\" like ?", "%#{to_search}%")
    else
      if from_search.present?
        return TravelDetail.where("\"from\" like ?", "%#{from_search}%")
      else
        if to_search.present?
          return TravelDetail.where("\"to\" like ?", "%#{to_search}%")
        else
          TravelDetail.all
        end
      end
    end
  end

  #validations
  validates :to, :from, :capacity, :arrival_time, :departure_time, presence: true
  validate :dates_check, :capacity_check

  def dates_check
    if arrival_time.present? && arrival_time < Time.now
      errors.add(:arrival_time, 'Arrival Date and Time Cannot be in the Past')
    end

    if departure_time.present? && departure_time < Time.now
      errors.add(:departure_time, 'Departure Date and Time Cannot be in the Past')
    end

    if departure_time.present? && arrival_time.present? && arrival_time <= departure_time
      errors.add(:arrival_time, 'Arrival Time cannot be earlier than Departure Time')
    end
  end

  def capacity_check
    if capacity < '0'
      errors.add(:capacity, 'Capacity cannot be negative')
    end
  end

end

app/controllers/api/v1/travel_details_controller.rb
module Api::V1
  class TravelDetailsController < Api::BaseController

    def index
      render json: TravelDetail.all
    end

    def show
      render json: TravelDetail.find_by(id: params[:id])
    end

    def create
      @travel_detail = @current_user.travel_details.new(travel_detail_params)

      if @travel_detail.save
        render json: @travel_detail
      else
        render json: @travel_detail.errors
      end
    end

    private
    def travel_detail_params
      params.require(:travel_detail).permit(:to, :from, :departure_time, :arrival_time, :capacity, :additional_message, :going_by)
    end

  end
end

# Dummy data for travel details
# travel_detail[from]:Karachi
# travel_detail[to]:Lahore
# travel_detail[departure_time]:2022-09-01T13:09:39.541Z
# travel_detail[arrival_time]:2022-09-03T13:09:39.541Z
# travel_detail[capacity]:100
# travel_detail[going_by]:Road
# travel_detail[user_id]:1
#

app/controllers/travel_details_controller.rb
class TravelDetailsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_travel_detail, only: [:edit, :update]

  # index action
  def index
    @travel_details = TravelDetail.search(params[:from_search], params[:to_search])
                                  .where.not(:user_id => current_user.id)
                                  .paginate(page: params[:page], per_page: 5)

    # format is optional
    respond_to do |format|
      format.html
      format.js
    end

  end

  def new
    @travel_detail = TravelDetail.new
  end

  def edit
    authorize @travel_detail
  end

  def create
    @travel_detail = current_user.travel_details.new(travel_detail_params)

    if @travel_detail.save
      flash[:info_toast] = 'Service Added To The List'
      redirect_to travel_details_path
    else
      render 'new'
    end
  end

  def update

    if @travel_detail.update(travel_detail_params)
      flash[:info_toast] = "Service Updated"
      redirect_to travel_details_path
    else
      render 'edit'
    end
  end

  def my_travel_details
    @travel_details = TravelDetail.get_current_user_travel_details(current_user.id).paginate(page: params[:page], per_page: 5)
    # format is optional
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def find_travel_detail
    @travel_detail = TravelDetail.find(params[:id])
  end

  def travel_detail_params
    params.require(:travel_detail).permit(:to, :from, :departure_time, :arrival_time, :capacity, :additional_message, :going_by, :from_latlng, :to_latlng)
  end

end

app/helpers/travel_details_helper.rb
module TravelDetailsHelper
end

app/views/travel_details/_form.html.erb
<div class=" container my-5" , style="width: 20cm">


  <h4 class="my-5">Add Travel Details</h4>

  <%= form_with model: @travel_detail, local: true do |f| %>

    <div class="input-group mb-4">
      <%= f.label 'Going From', class: 'input-group-text' %>
      <%= f.text_field :from, class: 'form-control' %>

      <% if @travel_detail.errors.messages[:from].any? %>
        <div style="color: #B00100" , class="form-control"><%= "'From' #{@travel_detail.errors.messages[:from][0]}" %></div>
      <% end %>
    </div>


    <div class="input-group my-4">
      <%= f.label 'Going To', class: 'input-group-text' %>
      <%= f.text_field :to, class: 'form-control' %>

      <% if @travel_detail.errors.messages[:to].any? %>
        <div style="color: #B00100" , class="form-control"><%= "'To' #{@travel_detail.errors.messages[:to][0]}" %></div>
      <% end %>
    </div>

    <div id="map" style="height: 200px; display: none"></div>


    <div class="input-group my-4">
      <%= f.label 'Departure Time', class: 'input-group-text' %>
      <%= f.datetime_field :departure_time, class: 'form-control' %>
    </div>

    <% if @travel_detail.errors.messages[:departure_time].any? %>
      <div style="color: #B00100" , class="mb-4"><%= "#{@travel_detail.errors.messages[:departure_time][0]}" %></div>
    <% end %>



    <div class="input-group mb-4">
      <%= f.label 'Arrival Time', class: 'input-group-text' %>
      <%= f.datetime_field :arrival_time, class: 'form-control' %>
    </div>

    <% if @travel_detail.errors.messages[:arrival_time].any? %>
      <div style="color: #B00100" , class="mb-4"><%= "#{@travel_detail.errors.messages[:arrival_time][0]}" %></div>
    <% end %>

    <div class="input-group mb-4">
      <%= f.label 'Capacity (KG)', class: 'input-group-text' %>
      <%= f.number_field :capacity, step: 0.5, class: 'form-control' %>

      <% if @travel_detail.errors.messages[:capacity].any? %>
        <div style="color: #B00100" , class="form-control"><%= "Capacity #{@travel_detail.errors.messages[:capacity][0]}" %></div>
      <% end %>
    </div>

    <div class="input-group mb-4">

      <%= f.label 'Going by', class: 'input-group-text' %>

      <div class="form-control">

        <%= f.radio_button :going_by, 'Road', class: 'form-check-input ms-3', checked: 'checked' %>
        <label class="form-check-label">
          Road
        </label>

        <%= f.radio_button :going_by, 'Air', class: 'form-check-input ms-3' %>
        <label class="form-check-label">
          Air
        </label>

      </div>
    </div>


    <div class="input-group mb-4">
      <%= f.label 'Additional Message', class: 'input-group-text' %>
      <%= f.text_area :additional_message, class: 'form-control' %>
    </div>

<!--    Hidden Fields-->
    <div class="details_from">
      <%= f.hidden_field :from_latlng,'data-geo' => "location" %>
    </div>

    <div class="details_to">
      <%= f.hidden_field :to_latlng,'data-geo' => "location" %>
    </div>

<!--    submit button-->
    <div class="">
      <%= f.submit 'Add Service', class: 'col-6 btn btn-primary' %>
    </div>

  <% end %>


</div>

app/views/travel_details/_travel_detail.html.erb
<div class="d-inline-flex mb-3 me-1 p-2 fw-semibold text-white bg-primary border border-primary  rounded-2">Traveller
  Details :
</div>
<div class="d-inline-flex mb-3 p-2  text-primary bg-primary bg-opacity-10 border border-primary border-opacity-10 rounded-2"><%= travel_detail.user.name %></div>
<div class="d-inline-flex mb-3 p-2  text-primary bg-primary bg-opacity-10 border border-primary border-opacity-10 rounded-2"><%= travel_detail.user.email %></div>
<div class="d-inline-flex mb-3 p-2  text-primary bg-primary bg-opacity-10 border border-primary border-opacity-10 rounded-2"><%= travel_detail.user.contact %></div>

<table class="table table-primary table-bordered  table-striped">
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Departure Date</th>
    <th>Arrival Date</th>
    <th>Capacity</th>
    <th>Going By</th>

  </tr>

  <tr>
    <td><%= travel_detail.from %></td>
    <td><%= travel_detail.to %></td>
    <td><%= travel_detail.departure_time.to_formatted_s(:long_ordinal) %></td>
    <td><%= travel_detail.arrival_time.to_formatted_s(:long_ordinal) %></td>
    <td><%= travel_detail.capacity %></td>
    <td><%= travel_detail.going_by %></td>
  </tr>
</table>


<% if travel_detail.additional_message.present? %>
  <div class="card" style="margin-bottom: 5px">
    <div class="card-body">
      <h5 class="card-title">Additional Message</h5>
      <p><%= travel_detail.additional_message %></p>
    </div>
  </div>
<% end %>

app/views/travel_details/_travel_details.html.erb
<div class="d-flex my-5">
  <%= form_with url: travel_details_path, remote: true, method: :get do %>
    <%= text_field_tag :from_search, params[:from_search], placeholder: "From", class: "form-control col-3  my-1" %>
    <%= text_field_tag :to_search, params[:to_search], placeholder: "To", class: "form-control col-3 my-1" %>
    <%= submit_tag 'Search', class: "btn btn-outline-success col-3 my-1" %>
  <% end %>
</div>


<% if @travel_details.any? %>
  <% @travel_details.each do |travel_detail| %>

    <div style="margin-bottom: 60px">

      <%= render 'travel_detail', locale = { travel_detail: travel_detail } %>

      <!--      Place Order Button or Details Button-->
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <% if travel_detail.user.id != current_user.id %>
          <%= link_to 'Place Order', new_travel_detail_order_path(travel_detail), class: 'btn btn-outline-danger me-md-2' %>
        <% else %>
          <%= link_to 'Details', travel_detail_orders_path(travel_detail), class: 'btn btn-outline-success me-md-2' %>
        <% end %>
      </div>

    </div>

  <% end %>
  <%= will_paginate @travel_details %>
<% else %>
  <h5 class="text-center no-service-available h-100">No Service Available</h5>
<% end %>

app/views/travel_details/current_user_travel_details.html.erb
<div class="container my-5" style="width: 70%">


  <% @travel_details.each do |travel_detail| %>

    <div style="margin-bottom: 60px">

      <%= render 'travel_detail', locale = {travel_detail: travel_detail}%>

      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= link_to 'Details', travel_detail_orders_path(travel_detail), class: 'btn btn-outline-success me-md-2' %>
      </div>

    </div>

  <% end %>

  <%= will_paginate @current_user_travel_details_travel_details_path %>


</div>

app/views/travel_details/edit.html.erb
<div class=" container mt-5", style="width: 20cm" >

  <h4 class="my-5">Add Travel Details</h4>

  <%= form_with model: @travel_detail ,local: true do |f| %>

    <div class="input-group mb-4">
      <%= f.label 'Going From', class:'input-group-text' %>
      <%= f.text_field :from , class:'form-control' %>

      <% if @travel_detail.errors.messages[:from].any? %>
        <div style="color: #B00100", class="form-control"><%="'From' #{@travel_detail.errors.messages[:from][0]}" %></div>
      <% end %>

    </div>


    <div class="input-group mb-4">
      <%= f.label 'Going To', class:'input-group-text' %>
      <%= f.text_field :to , class:'form-control' %>

      <% if @travel_detail.errors.messages[:to].any? %>
        <div style="color: #B00100", class="form-control"><%="'To' #{@travel_detail.errors.messages[:to][0]}" %></div>
      <% end %>

    </div>





    <div class="input-group mb-4">
      <%= f.label 'Departure Time', class:'input-group-text' %>
      <%= f.datetime_field :departure_time , class:'form-control' %>
    </div>

    <% if @travel_detail.errors.messages[:departure_time].any? %>
      <div style="color: #B00100", class="mb-4"><%="#{@travel_detail.errors.messages[:departure_time][0]}" %></div>
    <% end %>



    <div class="input-group mb-4">
      <%= f.label 'Arrival Time', class:'input-group-text' %>
      <%= f.datetime_field :arrival_time , class:'form-control' %>
    </div>

    <% if @travel_detail.errors.messages[:arrival_time].any? %>
      <div style="color: #B00100", class="mb-4"><%="#{@travel_detail.errors.messages[:arrival_time][0]}" %></div>
    <% end %>

    <div class="input-group mb-4">
      <%= f.label 'Capacity', class:'input-group-text' %>
      <%= f.text_field :capacity , class:'form-control' %>

      <% if @travel_detail.errors.messages[:capacity].any? %>
        <div style="color: #B00100", class="form-control"><%="Capacity #{@travel_detail.errors.messages[:capacity][0]}" %></div>
      <% end %>
    </div>

    <div class="input-group mb-4">

      <%= f.label 'Going by', class:'input-group-text' %>

      <div class="form-control">

        <%= f.radio_button :going_by, 'Road', class:'form-check-input ms-3', checked:'checked'  %>
        <label class="form-check-label">
          Road
        </label>

        <%= f.radio_button :going_by, 'Air', class:'form-check-input ms-3'%>
        <label class="form-check-label">
          Air
        </label>

      </div>
    </div>


    <div class="input-group mb-4">
      <%= f.label 'Additional Message', class:'input-group-text' %>
      <%= f.text_area :additional_message , class:'form-control' %>
    </div>


    <div class="">
      <%= f.submit 'Add Service', class: 'col-6 btn btn-primary' %>
    </div>

  <% end %>


</div>

app/views/travel_details/index.html.erb
<div class="container my-5" id="index_page" style="width: 70%">
  <%= render partial: 'travel_details' %>
</div>

app/views/travel_details/index.js.erb
$("#index_page").html("<%= j(render partial: 'travel_details') %>")

app/views/travel_details/my_travel_details.html.erb
<div class="container my-5" style="width: 70%">

  <% if @travel_details.any? %>

    <h3 class="my-5">My Services</h3>

    <% @travel_details.each do |travel_detail| %>

      <div style="margin-bottom: 60px">

        <%= render 'travel_detail', locale = { travel_detail: travel_detail } %>

        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <%= link_to 'Details', travel_detail_orders_path(travel_detail), class: 'btn btn-outline-success me-md-2' %>
        </div>

      </div>

    <% end %>
  <% else %>
    <h5 class="text-center no-service-available h-100">You have not added any service yet</h5>
  <% end %>

  <%= will_paginate @my_travel_details_travel_details_path %>


</div>

app/views/travel_details/new.html.erb
<%= render 'form' %>


<script>

    $('#travel_detail_from').geocomplete({
        types: ['locality'],
        details: ".details_from",
        detailsAttribute: "data-geo"
    }).bind('geocode:result', function () {
        if ($('#travel_detail_to').val() !== "") {
            setMap()
        }
    });

    $('#travel_detail_to').geocomplete({
        types: ['locality'],
        details: ".details_to",
        detailsAttribute: "data-geo"
    }).bind('geocode:result', function () {
        if ($('#travel_detail_from').val() !== "") {
            setMap()
        }
    });

    function setMap() {

        var map= document.getElementById("map");
        map.style.display = 'block'
        var defaultOptions = {zoom: 8}
        map = new google.maps.Map(map, defaultOptions);


        var directionsService = new google.maps.DirectionsService();
        var directionsDisplay = new google.maps.DirectionsRenderer();
        directionsDisplay.setMap(map);


        var start = $("#travel_detail_from").val();
        var end = $("#travel_detail_to").val();


        var request = {
            origin: start,
            destination: end,
            travelMode: 'DRIVING'
        };
        directionsService.route(request, function (result, status) {
            if (status === 'OK') {
                directionsDisplay.setDirections(result);
            }
        });
    }
</script>