config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :travel_details do
    get :my_travel_details, on: :collection
    resources :orders
  end

  root to: 'home#homepage'
  get 'homepage', to: 'home#homepage'
  # custom route for get current user orders
  # from home controller
  get :current_user_orders, to: 'home#current_user_orders'

  get :api_key, to: 'home#api_key'

  # Routes For API Calls
  namespace :api do
    namespace :v1 do
      resources :travel_details do
        resources :orders
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Courier Service</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item active">
          <%= link_to 'Home', homepage_path, class: "nav-link #{active_class(homepage_path)}" %>
        </li>

        <li>
          <%= link_to 'Add Service', new_travel_detail_path, class: "nav-link #{active_class(new_travel_detail_path)}" %>
        </li>

        <li>
          <%= link_to 'My Services', my_travel_details_travel_details_path, class: "nav-link #{active_class(my_travel_details_travel_details_path)} " %>
        </li>

        <li>
          <%= link_to 'Available Services', travel_details_path, class: "nav-link #{active_class(travel_details_path)}" %>
        </li>

        <li>
          <%= link_to 'My Orders', current_user_orders_path, class: "nav-link #{active_class(current_user_orders_path)}" %>
        </li>

      </ul>

      <form class="d-flex">

        <% if user_signed_in? %>
          <div class="form-control btn btn-danger me-2">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </div>
        <% else %>
          <div class="form-control btn btn-success me-2">
            <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
          </div>
          <div class="form-control btn btn-outline-success me-2">
            <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
          </div>

        <% end %>

      </form>
    </div>
  </div>
</nav>