config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :travel_details do
    get :my_travel_details, on: :collection
    resources :orders
  end

  root to: 'home#homepage'
  get 'homepage', to: 'home#homepage'
  # custom route for get current user orders
  # from home controller
  get :current_user_orders, to: 'home#current_user_orders'

  get :api_key, to: 'home#api_key'

  # Routes For API Calls
  namespace :api do
    namespace :v1 do
      resources :travel_details do
        resources :orders
      end
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  # Associations
  belongs_to :travel_detail
  belongs_to :user
  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items

  # scopes
  scope :get_current_user_orders, ->(current_user_id) { where(:user_id => current_user_id)}

  #validations
  validates :package_details, :weight, presence: true
  validate :check_capacity


  # Custom Validation
  def check_capacity

    if weight.to_f > travel_detail.capacity.to_f
      errors.add(:weight, "is greater than the capacity of service")
    end
  end

end

app/controllers/api/v1/orders_controller.rb
module Api::V1
  class OrdersController < Api::BaseController
    before_action :get_travel_detail

    def index
      if @travel_detail.nil?
        render json: { error: 'travel detail does not exists' }
      else
        @orders = @travel_detail.orders
        render json: @orders
      end
    end

    def show
      if @travel_detail.nil?
        render json: { error: 'travel detail does not exists' }
      else
        @order = @travel_detail.orders.find_by(id: params[:id])
        render json: @order
      end
    end

    def create
      @order = @travel_detail.orders.new(order_params)
      @order.user_id = @current_user.id

      if @order.save
        render json: @order, status: :created
      else
        render json: @order.errors
      end
    end

    private

    def get_travel_detail
      @travel_detail = TravelDetail.find_by(id: params[:travel_detail_id])
    end

    def order_params
      params.require(:order).permit(:package_details, :weight)
    end

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!
  before_action :get_travel_detail, only: [:new, :create, :index]

  def index
    @orders = @travel_detail.orders.all
  end


  def new
    @order = @travel_detail.orders.new
    authorize @order
  end

  def create
    @order = @travel_detail.orders.new(order_params)
    @order.user_id = current_user.id

    if @order.save
      # Sending email to user
      OrderMailer.with(user: current_user, travel_detail: @travel_detail, order: @order)
                 .order_placed_email.deliver_later

      flash[:info_toast] = "Order Added  to The Service"
      redirect_to travel_details_path
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:package_details, :weight, items_attributes: [:name])
  end

  def get_travel_detail
    @travel_detail = TravelDetail.find(params[:travel_detail_id])
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_item_fields.html.erb
<div class="input-group nested-fields my-1">

  <%= f.label 'Item Name', class: 'input-group-text' %>
  <%= f.text_field :name, class: 'form-control' %>

  <%# if f.errors.messages[:name].any? %>
<!--    <div style="color: #B00100" , class="form-control"><%#= "Weight #{f.errors.messages[:name][0]}" %></div>-->
  <%# end %>

  <%= link_to_remove_association 'Remove', f, class:'btn btn-danger' %>
</div>

app/views/orders/index.html.erb
<div class="container" >

  <h3 style="margin: 40px 0px 20px 0px" >Service Details</h3>

  <div >
    <%=  render 'travel_details/travel_detail', locale = {travel_detail: @travel_detail}%>

    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to 'Edit Details', edit_travel_detail_path(@travel_detail), class: 'btn btn-outline-success me-md-2' %>
    </div>
  </div>

  <h3 style="margin: 70px 0px 40px 0px" >Orders Placed on this Service</h3>

  <% if @orders.try(:any?) %>

    <% @orders.each do |order| %>

      <div class="row">

        <div class="col-3">
          <div class="card" style="width: 20rem;">
          <div class="card-header">
            Package Details
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= order.package_details %></li>
          </ul>
          <div class="card-header">
            Weight
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= order.weight %></li>
          </ul>
        </div>
        </div>

        <div class="col-3">
          <div class="card" style="width: 20rem">

            <div class="card-header">
              Customer Details
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><%= order.user.name %></li>
              <li class="list-group-item"><%= order.user.email %></li>
              <li class="list-group-item"><%= order.user.contact %></li>
            </ul>

          </div>
        </div>

      </div>

      <hr class="divider w-50" style="margin-bottom: 30px; margin-top: 30px"></hr>

    <% end %>

  <% else %>
    <h5>No Orders on this service yet</h5>
  <% end %>

</div>

app/views/orders/new.html.erb
<div class="container">

  <h3 style="margin: 40px 0px 20px 0px">Service Details</h3>

  <%= render 'travel_details/travel_detail', locale = { travel_detail: @travel_detail } %>




  <div
    class="container text-center border rounded bg-light mb-4  "
    style="width: 15cm; margin-top: 70px; padding: 20px"
  >

    <h3 style="margin: 10px 0px 30px 0px">Your Order Details</h3>

    <%= form_with model: [@travel_detail, @order], local: true do |f| %>

      <div class="mb-4">
        <div class="input-group">
          <%= f.label 'Package Details', class: 'input-group-text' %>
          <%= f.text_field :package_details, class: 'form-control' %>
        </div>
        <% if @order.errors.messages[:package_details].any? %>
          <div style="color: #B00100" , class="form-control"><%= "Package Detail #{@order.errors.messages[:package_details][0]}" %></div>
        <% end %>
      </div>

      <div class="mb-4">
        <div class="input-group">
          <%= f.label 'Weight', class: 'input-group-text' %>
          <%= f.number_field :weight, step: 0.5, class: 'form-control' %>
        </div>
        <% if @order.errors.messages[:weight].any? %>
          <div style="color: #B00100" , class="form-control"><%= "Weight #{@order.errors.messages[:weight][0]}" %></div>
        <% end %>
      </div>

<!--      Nested fields for Items-->
      <div class="mb-4">
        <%= f.fields_for :items do |item| %>
          <%= render 'item_fields', :f => item %>
        <% end %>

        <%= link_to_add_association 'Add Item', f, :items, class:'btn btn-outline-primary mt-2' %>

      </div>

      <div class="">
        <%= f.submit 'Add Order', class: 'col-6 btn btn-primary' %>
      </div>

    <% end %>

  </div>

</div>